program BusanaUtama;

uses
  Forms,
  dm in 'dm.pas' {DMFrm: TDataModule},
  main in 'Main.pas' {MainFrm},
  MyChild in 'MyChild.pas' {MyChildFrm},
  MyMemo in 'MyMemo.pas' {MyMemoFrm},
  MyWeb in 'MyWeb.pas' {MyWebFrm},
  BuktiBayar in 'BuktiBayar.pas' {BuktiBayarFrm},
  CekBGCair in 'CekBGCair.pas' {CekBGCairFrm},
  DaftarDepo in 'DaftarDepo.pas' {DaftarDepoFrm},
  DaftarEkspedisi in 'DaftarEkspedisi.pas' {DaftarEkspedisiFrm},
  DaftarItem in 'DaftarItem.pas' {DaftarItemFrm},
  DaftarJadwalKunjungan in 'DaftarJadwalKunjungan.pas' {DaftarJadwalKunjunganFrm},
  DaftarKaryawan in 'DaftarKaryawan.pas' {DaftarKaryawanFrm},
  DaftarKendaraan in 'DaftarKendaraan.pas' {DaftarKendaraanFrm},
  DaftarKonstanta in 'DaftarKonstanta.pas' {DaftarKonstantaFrm},
  DaftarMenu in 'DaftarMenu.pas' {DaftarMenuFrm},
  DaftarOutlet in 'DaftarOutlet.pas' {DaftarOutletFrm},
  DaftarPerkiraan in 'DaftarPerkiraan.pas' {DaftarPerkiraanFrm},
  DaftarPrinsipal in 'DaftarPrinsipal.pas' {DaftarPrinsipalFrm},
  DaftarSlsman in 'DaftarSlsman.pas' {DaftarSlsmanFrm},
  DiscREG in 'DiscREG.pas' {DiscREGFrm},
  DiscTPR in 'DiscTPR.pas' {DiscTPRFrm},
  DT in 'DT.pas' {DTFrm},
  DT2 in 'DT2.pas' {DT2Frm},
  Faktur in 'Faktur.pas' {FakturFrm},
  FakturGab in 'FakturGab.pas' {FakturGabFrm},
  FakturTerkirim in 'FakturTerkirim.pas' {FakturTerkirimFrm},
  Filter in 'Filter.pas' {FilterFrm},
  fMaster in 'fMaster.pas' {MasterFrm},
  GantiPass in 'GantiPass.pas' {GantiPassFrm},
  HargaBeli in 'HargaBeli.pas' {HargaBeliFrm},
  HargaJual in 'HargaJual.pas' {HargaJualFrm},
  InfoKartuPiutang in 'InfoKartuPiutang.pas' {InfoKartuPiutangFrm},
  InfoMutasiStok in 'InfoMutasiStok.pas' {InfoMutasiStokFrm},
  KartuPiutang in 'KartuPiutang.pas' {KartuPiutangFrm},
  KasKecil in 'KasKecil.pas' {KasKecilFrm},
  KoreksiStok in 'KoreksiStok.pas' {KoreksiStokFrm},
  LapLR in 'LapLR.pas' {LapLRFrm},
  OrderSales in 'OrderSales.pas' {OrderSalesFrm},
  OrderSalesHadiah in 'OrderSalesHadiah.pas' {OrderSalesHadiahFrm},
  PBDepoHO in 'PBDepoHO.pas' {PBDepoHOFrm},
  PembayaranAP in 'PembayaranAP.pas' {PembayaranAPFrm},
  PembayaranAR in 'PembayaranAR.pas' {PembayaranARFrm},
  PembayaranRetur in 'PembayaranRetur.pas' {PembayaranReturFrm},
  Pembelian in 'Pembelian.pas' {PembelianFrm},
  Pengiriman in 'Pengiriman.pas' {PengirimanFrm},
  PerintahMuat in 'PerintahMuat.pas' {PerintahMuatFrm},
  PindahLokasi in 'PindahLokasi.pas' {PindahLokasiFrm},
  PO in 'PO.pas' {POFrm},
  ReturPembelian in 'ReturPembelian.pas' {ReturPembelianFrm},
  JurnalMemo in 'JurnalMemo.pas' {JurnalMemoFrm},
  ReturPenjualan in 'ReturPenjualan.pas' {ReturPenjualanFrm},
  PIB in 'PIB.pas' {PIBFrm},
  xProcs in 'XPROCS.pas',
  DaftarItemImpor in 'DaftarItemImpor.pas' {DaftarItemImporFrm},
  BOM in 'BOM.pas' {BOMFrm},
  Pembelian2 in 'Pembelian2.pas' {Pembelian2Frm},
  DaftarItem3 in 'DaftarItem3.pas' {DaftarItem3Frm},
  RMVL_IN in 'RMVL_IN.pas' {RMVL_INFrm},
  RMVL_OUT in 'RMVL_OUT.pas' {RMVL_OUTFrm},
  InventoryControl in 'InventoryControl.pas' {InventoryControlFrm},
  SubKontrak in 'SubKontrak.pas' {SubKontrakFrm},
  HasilProduksi in 'HasilProduksi.pas' {HasilProduksiFrm},
  SerahTerimaBJ in 'SerahTerimaBJ.pas' {SerahTerimaBJFrm},
  PemakaianBahan in 'PemakaianBahan.pas' {PemakaianBahanFrm},
  SerahTerimaWaste in 'SerahTerimaWaste.pas' {SerahTerimaWasteFrm},
  SubKontrak2 in 'SubKontrak2.pas' {SubKontrak2Frm},
  KartuStokBahanKITE in 'KartuStokBahanKITE.pas' {KartuStokBahanKITEFrm},
  LogAktifitas in 'LogAktifitas.pas' {LogAktifitasFrm},
  Pembelian3 in 'Pembelian3.pas' {Pembelian3Frm},
  UmurPiutang in 'UmurPiutang.pas' {UmurPiutangFrm},
  Kontrak in 'Kontrak.pas' {KontrakFrm},
  SaldoRekening in 'SaldoRekening.pas' {SaldoRekeningFrm},
  Neraca in 'Neraca.pas' {NeracaFrm},
  LaporanBC in 'LaporanBC.pas' {LaporanBCFrm},
  InfoMutasiStokRev in 'InfoMutasiStokRev.pas' {InfoMutasiStokRevFrm},
  PenyelesaianWaste in 'PenyelesaianWaste.pas' {PenyelesaianWasteFrm},
  InfoMutasiStokBB in 'InfoMutasiStokBB.pas' {InfoMutasiStokBBFrm},
  InfoMutasiStokNBB in 'InfoMutasiStokNBB.pas' {InfoMutasiStokNBBFrm},
  TerimaBB in 'TerimaBB.pas' {TerimaBBFrm},
  DaftarItemWIP1 in 'DaftarItemWIP1.pas' {DaftarItemWIP1Frm},
  HasilCutting in 'HasilCutting.pas' {HasilCuttingFrm},
  InfoWIPCutting1 in 'InfoWIPCutting1.pas' {InfoWIPCutting1Frm},
  LoadingCutting in 'LoadingCutting.pas' {LoadingCuttingFrm},
  InfoWIPCutting2 in 'InfoWIPCutting2.pas' {InfoWIPCutting2Frm},
  JasaBordir in 'JasaBordir.pas' {JasaBordirFrm},
  TerimaJasaBordir in 'TerimaJasaBordir.pas' {TerimaJasaBordirFrm},
  InfoWIPCuttingSubkon in 'InfoWIPCuttingSubkon.pas' {InfoWIPCuttingSubkonFrm},
  WasteCutting in 'WasteCutting.pas' {WasteCuttingFrm},
  TerimaHslCutting in 'TerimaHslCutting.pas' {TerimaHslCuttingFrm},
  HasilSewing in 'HasilSewing.pas' {HasilSewingFrm},
  InfoWIPSewing1 in 'InfoWIPSewing1.pas' {InfoWIPSewing1Frm};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TDMFrm, DMFrm);
  Application.CreateForm(TMainFrm, MainFrm);
  Application.CreateForm(TMyWebFrm, MyWebFrm);
  Application.CreateForm(TFilterFrm, FilterFrm);
  Application.Run;
end.
